"""empty message

Revision ID: 350455daec5c
Revises: 6ad65c535112
Create Date: 2023-02-03 14:56:32.939378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350455daec5c'
down_revision = '6ad65c535112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('condition', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('condition'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('price')
    )
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_phone_number_key', 'cart', type_='unique')
    op.drop_constraint('cart_postal_code_key', 'cart', type_='unique')
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'])
    op.drop_column('cart', 'phone_number')
    op.drop_column('cart', 'postal_code')
    op.add_column('favorites', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_phone_number_key', 'favorites', type_='unique')
    op.drop_constraint('favorites_postal_code_key', 'favorites', type_='unique')
    op.create_foreign_key(None, 'favorites', 'products', ['product_id'], ['id'])
    op.drop_column('favorites', 'phone_number')
    op.drop_column('favorites', 'postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('postal_code', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('favorites', sa.Column('phone_number', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_unique_constraint('favorites_postal_code_key', 'favorites', ['postal_code'])
    op.create_unique_constraint('favorites_phone_number_key', 'favorites', ['phone_number'])
    op.drop_column('favorites', 'product_id')
    op.add_column('cart', sa.Column('postal_code', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('phone_number', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_unique_constraint('cart_postal_code_key', 'cart', ['postal_code'])
    op.create_unique_constraint('cart_phone_number_key', 'cart', ['phone_number'])
    op.drop_column('cart', 'product_id')
    op.drop_table('products')
    # ### end Alembic commands ###
