"""empty message

Revision ID: 8001531984b6
Revises: 9de18320cf35
Create Date: 2023-02-03 14:44:58.048310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8001531984b6'
down_revision = '9de18320cf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('postal_code')
    )
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=False))
    op.drop_constraint('user_adress_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['address'])
    op.drop_column('user', 'adress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adress', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_adress_key', 'user', ['adress'])
    op.drop_column('user', 'address')
    op.drop_table('favorites')
    # ### end Alembic commands ###
