"""empty message

Revision ID: 83363a7b7d5a
Revises: 6b752ee91706
Create Date: 2023-02-21 12:27:29.980300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83363a7b7d5a'
down_revision = '6b752ee91706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img3', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('img4', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('img4')
        batch_op.drop_column('img3')

    # ### end Alembic commands ###
