"""empty message

Revision ID: 94f3cfcbfe30
Revises: fe6a21767b58
Create Date: 2023-02-03 17:18:19.758979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f3cfcbfe30'
down_revision = 'fe6a21767b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birth',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'country',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'country',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'birth',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
