"""empty message

Revision ID: 9de18320cf35
Revises: ae7d71abb2ff
Create Date: 2023-02-03 14:38:11.544140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de18320cf35'
down_revision = 'ae7d71abb2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('birth', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('adress', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('postal_code', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['birth'])
    op.create_unique_constraint(None, 'user', ['country'])
    op.create_unique_constraint(None, 'user', ['adress'])
    op.create_unique_constraint(None, 'user', ['first_name'])
    op.create_unique_constraint(None, 'user', ['city'])
    op.create_unique_constraint(None, 'user', ['postal_code'])
    op.create_unique_constraint(None, 'user', ['phone_number'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'adress')
    op.drop_column('user', 'birth')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
